# PLidar data folder
dataDir: ''

# version of lidar data
# 1: glued by old algorithm with 30-m resolution
# 2: glued by new algorithm with 3.75-m resolution (default)
data_version: 1

# GDAS1 data folder
GDAS1Dir: ''

# radiosonde data folder
soundingDir: ''

# ERA-5 data folder
ERA5Dir: ''

# save folder
saveDir: ''
